const easyMediumWords = [
  { thai: "สวัสดี", english: "Hello" },
  { thai: "ขอบคุณ", english: "Thank you" },
  { thai: "ใช่", english: "Yes" },
  { thai: "ไม่ใช่", english: "No" },
  { thai: "หนังสือ", english: "Book" },
  { thai: "แมว", english: "Cat" },
  { thai: "บ้าน", english: "House" },
  { thai: "น้ำ", english: "Water" },
  { thai: "เพื่อน", english: "Friend" },
  { thai: "อาหาร", english: "Food" },
  { thai: "รถ", english: "Car" },
  { thai: "ดินสอ", english: "Pencil" },
  { thai: "กระเป๋า", english: "Bag" },
  { thai: "ต้นไม้", english: "Tree" },
  { thai: "สุนัข", english: "Dog" },
  { thai: "ปลา", english: "Fish" },
  { thai: "นก", english: "Bird" },
  { thai: "โต๊ะ", english: "Table" },
  { thai: "เก้าอี้", english: "Chair" },
  { thai: "ดวงอาทิตย์", english: "Sun" },
  { thai: "ดวงจันทร์", english: "Moon" },
  { thai: "ดาว", english: "Star" },
  { thai: "ลม", english: "Wind" },
  { thai: "ฝน", english: "Rain" },
  { thai: "ทะเล", english: "Sea" },
  { thai: "ภูเขา", english: "Mountain" },
  { thai: "ป่า", english: "Forest" },
  { thai: "โรงเรียน", english: "School" },
  { thai: "ครู", english: "Teacher" },
  { thai: "นักเรียน", english: "Student" },
  { thai: "เวลา", english: "Time" },
  { thai: "นาฬิกา", english: "Clock" },
  { thai: "ปากกา", english: "Pen" },
  { thai: "กระดาษ", english: "Paper" },
  { thai: "แก้ว", english: "Glass" },
  { thai: "ช้อน", english: "Spoon" },
  { thai: "ส้อม", english: "Fork" },
  { thai: "มีด", english: "Knife" },
  { thai: "ข้าว", english: "Rice" },
  { thai: "ขนมปัง", english: "Bread" },
  { thai: "เนื้อ", english: "Meat" },
  { thai: "ผัก", english: "Vegetable" },
  { thai: "ผลไม้", english: "Fruit" },
  { thai: "กล้วย", english: "Banana" },
  { thai: "แอปเปิ้ล", english: "Apple" },
  { thai: "องุ่น", english: "Grapes" },
  { thai: "มะม่วง", english: "Mango" },
  { thai: "แตงโม", english: "Watermelon" },
  { thai: "มะเขือเทศ", english: "Tomato" },
  { thai: "ถั่ว", english: "Beans" },
  { thai: "นม", english: "Milk" },
  { thai: "กาแฟ", english: "Coffee" },
  { thai: "ชา", english: "Tea" },
  { thai: "น้ำตาล", english: "Sugar" },
  { thai: "เกลือ", english: "Salt" },
  { thai: "พริก", english: "Chili" },
  { thai: "หอม", english: "Onion" },
  { thai: "กระเทียม", english: "Garlic" },
  { thai: "ถนน", english: "Street" },
  { thai: "สะพาน", english: "Bridge" },
  { thai: "ตลาด", english: "Market" },
  { thai: "ร้านค้า", english: "Shop" },
  { thai: "เงิน", english: "Money" },
  { thai: "ธนาคาร", english: "Bank" },
  { thai: "โรงแรม", english: "Hotel" },
  { thai: "สนามบิน", english: "Airport" },
  { thai: "หมอ", english: "Doctor" },
  { thai: "พยาบาล", english: "Nurse" },
  { thai: "ตำรวจ", english: "Police" },
  { thai: "นักบิน", english: "Pilot" },
  { thai: "นักร้อง", english: "Singer" },
];

const hardWords = [
  { thai: "เครื่องบิน", english: "Airplane" },
  { thai: "โรงพยาบาล", english: "Hospital" },
  { thai: "มหาวิทยาลัย", english: "University" },
  { thai: "โทรศัพท์", english: "Telephone" },
  { thai: "สถานีรถไฟ", english: "Train station" },
  { thai: "ธรรมชาติ", english: "Nature" },
  { thai: "คอมพิวเตอร์", english: "Computer" },
  { thai: "โทรทัศน์", english: "Television" },
  { thai: "เครื่องดนตรี", english: "Musical instrument" },
  { thai: "สถาปัตยกรรม", english: "Architecture" },
  { thai: "ปรัชญา", english: "Philosophy" },
  { thai: "พจนานุกรม", english: "Dictionary" },
  { thai: "อารยธรรม", english: "Civilization" },
  { thai: "จิตวิทยา", english: "Psychology" },
  { thai: "ภูมิศาสตร์", english: "Geography" },
  { thai: "คณิตศาสตร์", english: "Mathematics" },
  { thai: "สังคมวิทยา", english: "Sociology" },
  { thai: "พฤติกรรมศาสตร์", english: "Behavioral science" },
  { thai: "สัตวแพทย์", english: "Veterinarian" },
  { thai: "ชีววิทยา", english: "Biology" },
  { thai: "เคมี", english: "Chemistry" },
  { thai: "ฟิสิกส์", english: "Physics" },
  { thai: "วิศวกรรมศาสตร์", english: "Engineering" },
  { thai: "แพทยศาสตร์", english: "Medical science" },
  { thai: "เศรษฐศาสตร์", english: "Economics" },
  { thai: "การบริหารธุรกิจ", english: "Business administration" },
  { thai: "กฎหมาย", english: "Law" },
  { thai: "การศึกษา", english: "Education" },
  { thai: "โบราณคดี", english: "Archaeology" },
  { thai: "ดาราศาสตร์", english: "Astronomy" },
  { thai: "มนุษยศาสตร์", english: "Humanities" },
  { thai: "ศาสนา", english: "Religion" },
  { thai: "นาฏศิลป์", english: "Performing arts" },
  { thai: "สถิติ", english: "Statistics" },
  { thai: "เครื่องสำอาง", english: "Cosmetics" },
  { thai: "เทคโนโลยี", english: "Technology" },
  { thai: "ประชาธิปไตย", english: "Democracy" },
  { thai: "การปฏิวัติ", english: "Revolution" },
  { thai: "สาธารณสุข", english: "Public health" },
  { thai: "อุตสาหกรรม", english: "Industry" },
  { thai: "นโยบาย", english: "Policy" },
  { thai: "สถาปนิก", english: "Architect" },
];

export { easyMediumWords, hardWords };

  